version: '3.8'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    hostname: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    hostname: kafka
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      TOPICS_TO_CREATE: big-reports-requests,mailing
    command: sh -c "((sleep 5 && kafka-topics --create --bootstrap-server kafka:9092 --replication-factor 1 --partitions 1 --topic big-reports-requests)&) && /etc/confluent/docker/run ">
    #command: sh -c "((sleep 5 && for t in $(echo $TOPICS_TO_CREATE | sed "s/,/ /g"); do kafka-topics --create --bootstrap-server kafka:9092 --replication-factor 1 --partitions 1 --topic  "$t"; done)&) && /etc/confluent/docker/run ">
